general {
    disable_loading_bar = true
    hide_cursor = true
    grace = 0
    no_fade_in = false
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 8
    noise = 0.03
    contrast = 0.85
    brightness = 0.75
    vibrancy = 0.2
    vibrancy_darkness = 0.1
}

# Time
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M:%S")"
    color = rgba(f3eafeff)
    font_size = 120
    font_family = JetBrainsMono Nerd Font
    position = 0, 200
    halign = center
    valign = center
}

# Date
label {
    monitor =
    text = cmd[update:1000] echo "$(LC_TIME="pl_PL.UTF.8" date +"%A, %B %d %Y")"
    color = rgba(f595ffee)
    font_size = 24
    font_family = JetBrainsMono Nerd Font
    position = 0, 100
    halign = center
    valign = center
}

# User
label {
    monitor =
    text = $USER
    color = rgba(e66fffee)
    font_size = 18
    font_family = JetBrainsMono Nerd Font
    position = 0, -10
    halign = center
    valign = center
}
# Fingerprint auth 
auth {
    fingerprint:enabled = true
}

# Input field
input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgba(f595ffee)
    inner_color = rgba(101424aa)
    font_color = rgba(f3eafeff)
    fade_on_empty = false
    placeholder_text = <span foreground="##ffffff80">Enter Password...</span>
    hide_input = false
    position = 0, -100
    halign = center
    valign = center
}