# named rule syntax (Hyprland 0.53+)
# blur
layerrule {
    name = vicinae-blur
    blur = on
    ignore_alpha = 0
    match:namespace = vicinae
}

# disable animation for vicinae only
layerrule {
    name = vicinae-no-animation
    no_anim = on
    match:namespace = vicinae
} 

windowrule {
    name = kitty-blur
    match:class = ^(kitty)$
    opacity = 0.6
}

# anonymous rule syntax (Hyprland 0.53+)
# layerrule = blur on, ignore_alpha 0, match:namespace vicinae
# layerrule = no_anim on, match:namespace vicinae