[General]
Background=
MinimumVT=1
MaximumVT=8
Font=JetBrainsMono Nerd Font
ScreenWidth=1920
ScreenHeight=1080

[Theme]
Current=nazuna
ThemeDir=/usr/share/sddm/themes
DisableUserImage=false
FacesDir=/var/lib/sddm/faces

[Users]
MinimumUID=1000
MaximumUID=60000

[Autologin]
User=
Session=

[Wayland]
EnableHiDPI=true
CompositorCommand=
SessionCommand=%(cmdline)
MinimumVT=3
MaximumVT=6

[X11]
DisplayCommand=/usr/share/sddm/scripts/Xsetup
MinimumVT=7
MaximumVT=16
ServerArguments=-nolisten tcp -dpi 96
ServerDir=/usr/share/sddm/xsession
SessionCommand=%(cmdline)
StartX11=/usr/share/sddm/scripts/startx11session
MinimumDisplayNumber=0
MaximumDisplayNumber=1

